name: Apprise-Skill
skillMetadata:
  sections:
    - name: Notification services by tag and URL
      fields:
        - name: tagurl_label
          type: label
          label: >
            <p>
            For a detailed list of all supported services and how to configure the service urls please check the
            <a href="https://github.com/caronc/apprise/wiki">Apprise wiki</a>
            </p>
        - name: tag1
          type: text
          label: Service tag 1
          value: ""
          placeholder: Pushbullet
        - name: service1
          type: text
          label: Service URL 1
          value: ""
          placeholder: pbul://accesstoken
        - name: tag2
          type: text
          label: Service tag 2
          value: ""
          placeholder: Telegram
        - name: service2
          type: text
          label: Service URL 2
          value: ""
          placeholder: tgram://bottoken/ChatID
        - name: tag3
          type: text
          label: Service tag 3
          value: ""
          placeholder: Mailto
        - name: service3
          type: text
          label: Service URL 3
          value: ""
          placeholder: mailto://userid:pass@domain.com
    - name: Configuration file
      fields:
        - name: configfile_label
          type: label
          label: >
            <p>
            Specify a configuration file (.yaml or .txt) on a path that can be read by the user that Mycroft is running with (usually "mycroft").<br/>
            For config file usage instructions go to <a href="https://github.com/caronc/apprise/wiki/config">Apprise config manual page</a><br/>
            When filename does not begin with "/" the prefix "/opt/mycroft/skills/apprise-skill/" is added,
            assuming the config file is located in Apprise-Skills directory folder.
            </p>
        - name: configfile
          type: text
          label: Configuration file name
          value: ""
          placeholder: apprise.yaml
        - name: tags_label
          type: label
          label: >
            <p>
            When using a config file please use tags and specifiy all tags as comma seperated list here (please check correct spelling and matching upper/lower case).
            </p>
        - name: tags
          type: text
          label: List of tags defined in config file
          value: ""
          placeholder: Peter,Paul,Mary
