name: Apprise
skillMetadata:
  sections:
    - name: Options
      fields:
        - name: name1
          type: text
          label: Service Name #1
          value: ""
          placeholder: Pushbullet
        - name: service1
          type: text
          label: Service URL #1
          value: ""
          placeholder: pbul://accesstoken
        - name: name2
          type: text
          label: Service Name #2
          value: ""
          placeholder: Telegram
        - name: service2
          type: text
          label: Service URL #2
          value: ""
          placeholder: tgram://bottoken/ChatID
        - name: name3
          type: text
          label: Service Name #3
          value: ""
          placeholder: Mailto
        - name: service3
          type: text
          label: Service URL #3
          value: ""
          placeholder: mailto://userid:pass@domain.com
